version: "2"

services:
  bff-service:
    build: 
      context: .
      dockerfile: ./build/bff/Dockerfile
    networks:
      - shopnetwork
    ports:
      - 127.0.0.1:5000:5000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - cart-service
      - catalog-service
      - payment-service
  cart-service:
    build: 
      context: .
      dockerfile: ./build/cart/Dockerfile
    networks:
      - shopnetwork
    expose:
      - "50052"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - catalog-service
      - payment-service
      - redis
      - rabbitmq
  catalog-service:
    build: 
      context: .
      dockerfile: ./build/catalog/Dockerfile
    networks:
      - shopnetwork
    expose:
      - "50051"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - rabbitmq
  payment-service:
    build: 
      context: .
      dockerfile: ./build/payment/Dockerfile
    networks:
      - shopnetwork
    expose:
      - "50053"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - rabbitmq
  mongo3:
    hostname: mongo3
    image: mongo:5.0.5-focal
    networks:
      - shopnetwork
    volumes:
      - ./data/mongo3:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "shop-mongo-set" ]
  mongo2:
    hostname: mongo2
    image: mongo:5.0.5-focal
    networks:
      - shopnetwork
    volumes:
      - ./data/mongo2:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "shop-mongo-set" ]
  mongo1:
    hostname: mongo1
    image: mongo:5.0.5-focal
    networks:
      - shopnetwork
    volumes:
      - ./data/mongo1:/data/db
    depends_on:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "shop-mongo-set" ]
  mongo-setup:
    image: mongo:5.0.5-focal
    networks:
      - shopnetwork
    volumes:
      - ./script:/script
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: ["/script/setup.sh"]
  redis:
    image: redis:6.2.6-alpine
    networks:
      - shopnetwork
  rabbitmq:
    image: rabbitmq:3.9.11-management
    networks:
      - shopnetwork
    ports:
      - 15672:15672

networks:
  shopnetwork:
